genesis_id = ""
system = "Privatix"
dependencies = ["Ethereum"]
icon = "privatix"

[token]
name = "privatix token"
symbol = "​PRIX"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Internet Bandwidth Marketplace on Blockchain"

[crowdsales]
start_date = "2017-10-19T14:00:00"
end_date = "2017-11-16T14:00:00"
end_date_plan = "2017-11-16T14:00:00"
genesis_address = [""]
funding_terms = "https://dxw4crzwfgmzw.cloudfront.net/site/Token-sale-policy.pdf"
funding_url = "https://privatix.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "privatix.io"
url = "https://privatix.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Privatix Whitepaper"
url = "https://dxw4crzwfgmzw.cloudfront.net/whitepaper/PRIVATIX-WHITEPAPER.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Privatix GitHub"
url = "https://github.com/Privatix"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Privatix Blog"
url = "https://medium.com/privatix"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2140597"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Privatix1"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Privatix Telegram"
url = "https://t.me/Privatix"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/privatix"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/privatix.ltd"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC45KNwm-mmHADAR6jylrklg"
icon = "youtube.png"
tags = ["News"]
